version: "3"

services:
  java_puro_db:
    container_name: java_puro_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: java_puro_db
      POSTGRES_USER: java_puro_db
      POSTGRES_DB: crebito
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/script.sql
