version: "3.5"

services:

  java-puro-db:
    container_name: java-puro-db
    image: postgres:latest
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    environment:
      POSTGRES_PASSWORD: java_puro_db
      POSTGRES_USER: java_puro_db
      POSTGRES_DB: crebito
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/script.sql

  java-puro-one: &java-puro-api
    hostname: java-puro-one
    image: rinha-de-backend-2024-q1-java-puro:latest
    container_name: java-puro-one
    environment:
      DATABASE_URL: jdbc:postgresql://java-puro-db:5432/crebito
    ports:
      - "8081:8080"
  java-puro-two:
    <<: *java-puro-api
    hostname: java-puro-two
    container_name: java-puro-two
    ports:
      - "8082:8080"

  nginx-java-puro-load-balance:
    container_name: nginx-java-puro-load-balance
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - java-puro-one
      - java-puro-two
    ports:
      - "9999:9999"

networks:
  default:
    driver: bridge
    name: rinha-nginx-java-puro-2024-q1